#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/group-volume/users/jaden.ju/Sources/ImageCropping}"
RUN_NAME="${RUN_NAME:?RUN_NAME required}"
OUT_BASE="${OUT_BASE:-artifacts/mobilecropnet_v4/quality_first_20260428/quality_relaxed}"
OUT_DIR="${OUT_DIR:-${OUT_BASE}/${RUN_NAME}}"
TRAIN_JSONL="${TRAIN_JSONL:-artifacts/mobilecropnet_v4/quality_first_20260428/blended_public_uctr_labels/train_blended_public_uctr.jsonl}"
VAL_JSONL="${VAL_JSONL:-artifacts/mobilecropnet_v4/quality_first_20260428/blended_public_uctr_labels/val_blended_public_uctr.jsonl}"
EVAL_JSONL="${EVAL_JSONL:-data/SSTK/Full_10000/artifacts/training_labels_uctr_stage3_product_ar_260422_hashsplit_80_10_10_260422/val/train_conditional_detr_batch.jsonl}"
INIT_CHECKPOINT="${INIT_CHECKPOINT:-}"
INIT_CHECKPOINT_SKIP_PREFIXES="${INIT_CHECKPOINT_SKIP_PREFIXES:-}"
TRAINABLE_PREFIXES="${TRAINABLE_PREFIXES:-}"
BACKBONE_PRETRAINED="${BACKBONE_PRETRAINED:-auto}"

MODEL_PROFILE="${MODEL_PROFILE:-quality_swinv2b_384}"
INPUT_SIZE="${INPUT_SIZE:-}"
CANDIDATE_K="${CANDIDATE_K:-}"
PROPOSAL_Q="${PROPOSAL_Q:-}"
TOKEN_DIM="${TOKEN_DIM:-}"
BACKBONE_NAME="${BACKBONE_NAME:-}"
IMAGE_MEAN="${IMAGE_MEAN:-}"
IMAGE_STD="${IMAGE_STD:-}"
EPOCHS="${EPOCHS:-2}"
BATCH_SIZE="${BATCH_SIZE:-6}"
LR="${LR:-8e-6}"
MIN_LR="${MIN_LR:-1e-6}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-1}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.0}"
NUM_WORKERS="${NUM_WORKERS:-4}"
MAX_TRAIN_ROWS="${MAX_TRAIN_ROWS:-24000}"
MAX_VAL_ROWS="${MAX_VAL_ROWS:-3200}"
AUDIT_BATCH_SIZE="${AUDIT_BATCH_SIZE:-12}"
DIRECT_BATCH_SIZE="${DIRECT_BATCH_SIZE:-12}"
MAX_GATE_ROWS="${MAX_GATE_ROWS:-3200}"
PAIRWISE_JSONL="${PAIRWISE_JSONL:-}"
VAL_PAIRWISE_JSONL="${VAL_PAIRWISE_JSONL:-}"
MAX_PAIRWISE_PAIRS="${MAX_PAIRWISE_PAIRS:-32}"

ROUTE1="${ROUTE1:-artifacts/mobilecropnet_v4/quality_first_20260427/route_experts/swinv2b384_uctr_r1-20260427/best.pt}"
ROUTE2="${ROUTE2:-artifacts/mobilecropnet_v4/quality_first_20260427/route_experts/cnv2l512_uctr_r2-20260427/best.pt}"
ROUTE3="${ROUTE3:-artifacts/mobilecropnet_v4/quality_first_20260427/route_experts/eva02l448_m38m_uctr_r1-20260427/best.pt}"
ROUTE_EXPERT_DISTILL_WEIGHTS="${ROUTE_EXPERT_DISTILL_WEIGHTS:-0.50,0.25,0.25}"
ROUTE_EXPERT_DISTILL_WEIGHT="${ROUTE_EXPERT_DISTILL_WEIGHT:-4.2}"
ROUTE_EXPERT_DISTILL_HARD_WEIGHT="${ROUTE_EXPERT_DISTILL_HARD_WEIGHT:-0.6}"
EMBED_ROUTE="${EMBED_ROUTE:-${ROUTE1}}"

ROUTE_HEAD_DEPTH="${ROUTE_HEAD_DEPTH:-3}"
ROUTE_HEAD_HIDDEN_MULT="${ROUTE_HEAD_HIDDEN_MULT:-0.7}"
ROUTE_DECODE_MODE="${ROUTE_DECODE_MODE:-hierarchical}"
ROUTE_IMAGE_RESIDUAL="${ROUTE_IMAGE_RESIDUAL:-0}"
ROUTE_IMAGE_RESIDUAL_WEIGHT="${ROUTE_IMAGE_RESIDUAL_WEIGHT:-1.0}"
ROUTE_CONDITION_CANDIDATE_SCORES="${ROUTE_CONDITION_CANDIDATE_SCORES:-0}"
ROUTE_CONDITION_DETACH="${ROUTE_CONDITION_DETACH:-1}"
RETURN_SCORE_HEAD="${RETURN_SCORE_HEAD:-0}"
RETURN_SCORE_HEAD_DEPTH="${RETURN_SCORE_HEAD_DEPTH:-1}"
RETURN_SCORE_HEAD_HIDDEN_MULT="${RETURN_SCORE_HEAD_HIDDEN_MULT:-0.5}"
RETURN_SCORE_ACTION_SOURCE_BIAS="${RETURN_SCORE_ACTION_SOURCE_BIAS:-0}"
RETURN_SCORE_DECISION_SOURCE_BIAS="${RETURN_SCORE_DECISION_SOURCE_BIAS:-0}"
RETURN_SCORE_DECISION_SOURCE_DETACH="${RETURN_SCORE_DECISION_SOURCE_DETACH:-1}"
RETURN_SCORE_DECISION_SOURCE_MAX_SCALE="${RETURN_SCORE_DECISION_SOURCE_MAX_SCALE:-2.0}"
RETURN_SCORE_DECISION_SOURCE_FROM_SOURCE_HEAD="${RETURN_SCORE_DECISION_SOURCE_FROM_SOURCE_HEAD:-0}"
RETURN_SCORE_DECISION_CONDITIONED="${RETURN_SCORE_DECISION_CONDITIONED:-0}"
RETURN_SCORE_DECISION_CONDITIONED_MASK_VALUE="${RETURN_SCORE_DECISION_CONDITIONED_MASK_VALUE:--10000.0}"
RETURN_SCORE_DECISION_CONDITIONED_FROM_SOURCE_HEAD="${RETURN_SCORE_DECISION_CONDITIONED_FROM_SOURCE_HEAD:-0}"
RETURN_SCORE_SOURCE_MIXTURE="${RETURN_SCORE_SOURCE_MIXTURE:-0}"
RETURN_SCORE_SOURCE_MIXTURE_STRENGTH="${RETURN_SCORE_SOURCE_MIXTURE_STRENGTH:-1.0}"
RETURN_SCORE_SOURCE_MIXTURE_DETACH="${RETURN_SCORE_SOURCE_MIXTURE_DETACH:-1}"
RETURN_SCORE_SOURCE_MIXTURE_FROM_SOURCE_HEAD="${RETURN_SCORE_SOURCE_MIXTURE_FROM_SOURCE_HEAD:-0}"
RETURN_SCORE_SOURCE_MIXTURE_GAP_THRESHOLD="${RETURN_SCORE_SOURCE_MIXTURE_GAP_THRESHOLD:-}"
RETURN_SCORE_SOURCE_MIXTURE_GAP_MASK_VALUE="${RETURN_SCORE_SOURCE_MIXTURE_GAP_MASK_VALUE:--10000.0}"
RETURN_SCORE_SOURCE_GATE="${RETURN_SCORE_SOURCE_GATE:-0}"
RETURN_SCORE_SOURCE_GATE_HIDDEN_MULT="${RETURN_SCORE_SOURCE_GATE_HIDDEN_MULT:-0.5}"
RETURN_SCORE_SOURCE_GATE_STRENGTH="${RETURN_SCORE_SOURCE_GATE_STRENGTH:-1.0}"
RETURN_SCORE_SOURCE_GATE_DETACH="${RETURN_SCORE_SOURCE_GATE_DETACH:-1}"
RETURN_SCORE_SOURCE_GATE_SUBJECT_STATE="${RETURN_SCORE_SOURCE_GATE_SUBJECT_STATE:-0}"
RETURN_SCORE_SOURCE_GATE_SUBJECT_DETACH="${RETURN_SCORE_SOURCE_GATE_SUBJECT_DETACH:-1}"
RETURN_SCORE_SOURCE_GATE_LOGIT_THRESHOLD="${RETURN_SCORE_SOURCE_GATE_LOGIT_THRESHOLD:-0.0}"
RETURN_SCORE_SOURCE_SPECIFIC_HEAD="${RETURN_SCORE_SOURCE_SPECIFIC_HEAD:-0}"
RETURN_SCORE_SOURCE_SPECIFIC_HIDDEN_MULT="${RETURN_SCORE_SOURCE_SPECIFIC_HIDDEN_MULT:-0.5}"
RETURN_SCORE_CONTEXT_HEAD="${RETURN_SCORE_CONTEXT_HEAD:-0}"
RETURN_SCORE_CONTEXT_HIDDEN_MULT="${RETURN_SCORE_CONTEXT_HIDDEN_MULT:-0.5}"
RETURN_SCORE_CONTEXT_DETACH="${RETURN_SCORE_CONTEXT_DETACH:-1}"
RETURN_SCORE_POLICY_MATCH_HEAD="${RETURN_SCORE_POLICY_MATCH_HEAD:-0}"
RETURN_SCORE_POLICY_MATCH_HIDDEN_MULT="${RETURN_SCORE_POLICY_MATCH_HIDDEN_MULT:-0.5}"
RETURN_SCORE_POLICY_MATCH_DETACH="${RETURN_SCORE_POLICY_MATCH_DETACH:-1}"
RETURN_SCORE_POLICY_SOURCE_HEAD="${RETURN_SCORE_POLICY_SOURCE_HEAD:-0}"
RETURN_SCORE_POLICY_SOURCE_HIDDEN_MULT="${RETURN_SCORE_POLICY_SOURCE_HIDDEN_MULT:-0.5}"
RETURN_SCORE_POLICY_SOURCE_DETACH="${RETURN_SCORE_POLICY_SOURCE_DETACH:-1}"
RETURN_SCORE_COMPETITION_HEAD="${RETURN_SCORE_COMPETITION_HEAD:-0}"
RETURN_SCORE_COMPETITION_HIDDEN_MULT="${RETURN_SCORE_COMPETITION_HIDDEN_MULT:-0.5}"
RETURN_SCORE_COMPETITION_DETACH="${RETURN_SCORE_COMPETITION_DETACH:-1}"
RETURN_SCORE_SET_REFINER_HEAD="${RETURN_SCORE_SET_REFINER_HEAD:-0}"
RETURN_SCORE_SET_REFINER_HIDDEN_MULT="${RETURN_SCORE_SET_REFINER_HIDDEN_MULT:-1.0}"
RETURN_SCORE_SET_REFINER_LAYERS="${RETURN_SCORE_SET_REFINER_LAYERS:-1}"
RETURN_SCORE_SET_REFINER_DETACH="${RETURN_SCORE_SET_REFINER_DETACH:-1}"
RETURN_SCORE_ACTION_DECODER_HEAD="${RETURN_SCORE_ACTION_DECODER_HEAD:-0}"
RETURN_SCORE_ACTION_DECODER_HIDDEN_MULT="${RETURN_SCORE_ACTION_DECODER_HIDDEN_MULT:-1.0}"
RETURN_SCORE_ACTION_DECODER_LAYERS="${RETURN_SCORE_ACTION_DECODER_LAYERS:-1}"
RETURN_SCORE_ACTION_DECODER_DETACH="${RETURN_SCORE_ACTION_DECODER_DETACH:-1}"
RETURN_SCORE_ACTION_DECODER_SUBJECT_STATE="${RETURN_SCORE_ACTION_DECODER_SUBJECT_STATE:-0}"
RETURN_SCORE_ACTION_DECODER_SUBJECT_DETACH="${RETURN_SCORE_ACTION_DECODER_SUBJECT_DETACH:-1}"
RETURN_SCORE_ACTION_DECODER_REPLACE="${RETURN_SCORE_ACTION_DECODER_REPLACE:-0}"
SUBJECT_BOX_TARGET_SOURCE="${SUBJECT_BOX_TARGET_SOURCE:-support_latent}"
SUBJECT_BOX_VALID_TARGET_MODE="${SUBJECT_BOX_VALID_TARGET_MODE:-route_gated}"
SUBJECT_BOX_VALID_RELIABILITY_MIN="${SUBJECT_BOX_VALID_RELIABILITY_MIN:-0.25}"
SUBJECT_BOX_REFINE_WITH_PROPOSALS="${SUBJECT_BOX_REFINE_WITH_PROPOSALS:-0}"
SUBJECT_VALID_ROUTE_CALIBRATOR="${SUBJECT_VALID_ROUTE_CALIBRATOR:-0}"
SUBJECT_VALID_ROUTE_CALIBRATOR_HIDDEN_MULT="${SUBJECT_VALID_ROUTE_CALIBRATOR_HIDDEN_MULT:-0.5}"
SUBJECT_VALID_ROUTE_CALIBRATOR_DETACH="${SUBJECT_VALID_ROUTE_CALIBRATOR_DETACH:-1}"
SUBJECT_VALID_THRESHOLD="${SUBJECT_VALID_THRESHOLD:-0.3}"
SUBJECT_VALID_POLICY="${SUBJECT_VALID_POLICY:-route_and_conf}"

SCORE_WEIGHT="${SCORE_WEIGHT:-0.46}"
LISTWISE_WEIGHT="${LISTWISE_WEIGHT:-0.24}"
PAIRWISE_WEIGHT="${PAIRWISE_WEIGHT:-0.0}"
EXPLICIT_PAIRWISE_WEIGHT="${EXPLICIT_PAIRWISE_WEIGHT:-0.2}"
POSITIVE_WEIGHT="${POSITIVE_WEIGHT:-0.36}"
RISK_WEIGHT="${RISK_WEIGHT:-0.25}"
TOP1_RISK_WEIGHT="${TOP1_RISK_WEIGHT:-0.25}"
TOP_RETURN_WEIGHT="${TOP_RETURN_WEIGHT:-0.18}"
RAW_TOP_RETURN_WEIGHT="${RAW_TOP_RETURN_WEIGHT:-0.0}"
RETURN_SCORE_WEIGHT="${RETURN_SCORE_WEIGHT:-0.0}"
RETURN_LISTWISE_WEIGHT="${RETURN_LISTWISE_WEIGHT:-0.0}"
RETURN_POSITIVE_WEIGHT="${RETURN_POSITIVE_WEIGHT:-0.0}"
RETURN_POSITIVE_MARGIN_WEIGHT="${RETURN_POSITIVE_MARGIN_WEIGHT:-0.0}"
RETURN_POSITIVE_MARGIN="${RETURN_POSITIVE_MARGIN:-0.2}"
RETURN_RISK_SUPPRESSION_WEIGHT="${RETURN_RISK_SUPPRESSION_WEIGHT:-0.0}"
RETURN_RISK_SUPPRESSION_MARGIN="${RETURN_RISK_SUPPRESSION_MARGIN:-0.2}"
RETURN_EXACT_WEIGHT="${RETURN_EXACT_WEIGHT:-0.0}"
RETURN_EXACT_MIN_GAP="${RETURN_EXACT_MIN_GAP:-0.0}"
RETURN_TARGET_MODE="${RETURN_TARGET_MODE:-score}"
RETURN_EXPLICIT_PAIRWISE_WEIGHT="${RETURN_EXPLICIT_PAIRWISE_WEIGHT:-0.0}"
RETURN_EXPLICIT_PAIRWISE_MARGIN="${RETURN_EXPLICIT_PAIRWISE_MARGIN:-0.0}"
TEACHER_DISTILL_WEIGHT="${TEACHER_DISTILL_WEIGHT:-0.0}"
TEACHER_DISTILL_TEMPERATURE="${TEACHER_DISTILL_TEMPERATURE:-0.12}"
TOPK_COVERAGE_WEIGHT="${TOPK_COVERAGE_WEIGHT:-0.0}"
TOPK_COVERAGE_K="${TOPK_COVERAGE_K:-4}"
TOPK_COVERAGE_TEMPERATURE="${TOPK_COVERAGE_TEMPERATURE:-0.12}"
MACRO_WEIGHT="${MACRO_WEIGHT:-0.04}"
CHECKLIST_CLASS_WEIGHT="${CHECKLIST_CLASS_WEIGHT:-0.02}"
CHECKLIST_APPLICABILITY_WEIGHT="${CHECKLIST_APPLICABILITY_WEIGHT:-0.02}"
DETAIL_SCORE_WEIGHT="${DETAIL_SCORE_WEIGHT:-0.02}"
WHY_TAG_WEIGHT="${WHY_TAG_WEIGHT:-0.02}"
ROUTE_WEIGHT="${ROUTE_WEIGHT:-12.0}"
ROUTE_OBJECT_SINGLE_MARGIN_WEIGHT="${ROUTE_OBJECT_SINGLE_MARGIN_WEIGHT:-0.0}"
ROUTE_OBJECT_SINGLE_MARGIN="${ROUTE_OBJECT_SINGLE_MARGIN:-0.18}"
ROUTE_FOCAL_GAMMA="${ROUTE_FOCAL_GAMMA:-0.0}"
ROUTE_HIERARCHY_WEIGHT="${ROUTE_HIERARCHY_WEIGHT:-0.35}"
ROUTE_CARDINALITY_WEIGHT="${ROUTE_CARDINALITY_WEIGHT:-0.25}"
TRAIN_ROUTE_BALANCED_SAMPLER_POWER="${TRAIN_ROUTE_BALANCED_SAMPLER_POWER:-1.0}"
TRAIN_ROUTE_BALANCED_SAMPLER_MIN_WEIGHT="${TRAIN_ROUTE_BALANCED_SAMPLER_MIN_WEIGHT:-0.25}"
TRAIN_ROUTE_BALANCED_SAMPLER_MAX_WEIGHT="${TRAIN_ROUTE_BALANCED_SAMPLER_MAX_WEIGHT:-4.0}"
TRAIN_DECISION_SOURCE_BALANCED_SAMPLER="${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER:-0}"
TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_POWER="${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_POWER:-1.0}"
TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_MIN_WEIGHT="${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_MIN_WEIGHT:-0.25}"
TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_MAX_WEIGHT="${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_MAX_WEIGHT:-4.0}"
DECISION_WEIGHT="${DECISION_WEIGHT:-0.12}"
DECISION_CROP_REBALANCE="${DECISION_CROP_REBALANCE:-0}"
DECISION_CROP_REBALANCE_MAX_WEIGHT="${DECISION_CROP_REBALANCE_MAX_WEIGHT:-4.0}"
ACTION_CONSISTENCY_WEIGHT="${ACTION_CONSISTENCY_WEIGHT:-0.34}"
ACTION_CONSISTENCY_MARGIN="${ACTION_CONSISTENCY_MARGIN:-0.15}"
ACTION_SOURCE_BALANCED="${ACTION_SOURCE_BALANCED:-0}"
ACTION_SOURCE_BALANCE_MAX_WEIGHT="${ACTION_SOURCE_BALANCE_MAX_WEIGHT:-4.0}"
ACTION_SOURCE_CROP_WEIGHT_MULT="${ACTION_SOURCE_CROP_WEIGHT_MULT:-1.0}"
ACTION_RETURN_JOINT_WEIGHT="${ACTION_RETURN_JOINT_WEIGHT:-0.0}"
ACTION_RETURN_JOINT_SCORE_MARGIN="${ACTION_RETURN_JOINT_SCORE_MARGIN:-0.03}"
ACTION_RETURN_JOINT_LOGIT_MARGIN="${ACTION_RETURN_JOINT_LOGIT_MARGIN:-0.20}"
ACTION_RETURN_JOINT_TEMPERATURE="${ACTION_RETURN_JOINT_TEMPERATURE:-0.12}"
RETURN_SOURCE_MARGIN_WEIGHT="${RETURN_SOURCE_MARGIN_WEIGHT:-0.0}"
RETURN_SOURCE_MARGIN_LOGIT_MARGIN="${RETURN_SOURCE_MARGIN_LOGIT_MARGIN:-0.25}"
RETURN_SOURCE_MARGIN_BALANCED="${RETURN_SOURCE_MARGIN_BALANCED:-0}"
RETURN_SOURCE_MARGIN_BALANCE_MAX_WEIGHT="${RETURN_SOURCE_MARGIN_BALANCE_MAX_WEIGHT:-4.0}"
RETURN_SOURCE_MARGIN_CROP_WEIGHT_MULT="${RETURN_SOURCE_MARGIN_CROP_WEIGHT_MULT:-1.0}"
DECISION_UTILITY_ALIGN_WEIGHT="${DECISION_UTILITY_ALIGN_WEIGHT:-0.12}"
POLICY_SCORE_WEIGHT="${POLICY_SCORE_WEIGHT:-0.18}"
DECISION_SOURCE_HEAD="${DECISION_SOURCE_HEAD:-0}"
DECISION_SOURCE_LOGIT_THRESHOLD="${DECISION_SOURCE_LOGIT_THRESHOLD:-0.0}"
DECISION_SOURCE_PAIR_HEAD="${DECISION_SOURCE_PAIR_HEAD:-0}"
DECISION_SOURCE_PAIR_HIDDEN_MULT="${DECISION_SOURCE_PAIR_HIDDEN_MULT:-0.5}"
DECISION_SOURCE_PAIR_AFTER_RETURN_DELTAS="${DECISION_SOURCE_PAIR_AFTER_RETURN_DELTAS:-0}"
DECISION_SOURCE_PAIR_SUBJECT_STATE="${DECISION_SOURCE_PAIR_SUBJECT_STATE:-0}"
DECISION_SOURCE_PAIR_SUBJECT_DETACH="${DECISION_SOURCE_PAIR_SUBJECT_DETACH:-1}"
DECISION_SOURCE_WEIGHT="${DECISION_SOURCE_WEIGHT:-0.0}"
DECISION_SOURCE_BALANCED_BCE="${DECISION_SOURCE_BALANCED_BCE:-0}"
DECISION_SOURCE_CROP_REBALANCE_MAX_WEIGHT="${DECISION_SOURCE_CROP_REBALANCE_MAX_WEIGHT:-4.0}"
DECISION_SOURCE_FOCAL_GAMMA="${DECISION_SOURCE_FOCAL_GAMMA:-0.0}"
DECISION_SOURCE_FOCAL_ALPHA="${DECISION_SOURCE_FOCAL_ALPHA:-}"
DECISION_SOURCE_MARGIN_WEIGHT="${DECISION_SOURCE_MARGIN_WEIGHT:-0.0}"
DECISION_SOURCE_LOGIT_MARGIN="${DECISION_SOURCE_LOGIT_MARGIN:-0.35}"
DECISION_SOURCE_MARGIN_BALANCED="${DECISION_SOURCE_MARGIN_BALANCED:-0}"
DECISION_SOURCE_MARGIN_BALANCE_MAX_WEIGHT="${DECISION_SOURCE_MARGIN_BALANCE_MAX_WEIGHT:-4.0}"
DECISION_SOURCE_MARGIN_CROP_WEIGHT_MULT="${DECISION_SOURCE_MARGIN_CROP_WEIGHT_MULT:-1.0}"
DECISION_SOURCE_PAIR_SUPERVISION_WEIGHT="${DECISION_SOURCE_PAIR_SUPERVISION_WEIGHT:-0.0}"
DECISION_SOURCE_PAIR_MARGIN_WEIGHT="${DECISION_SOURCE_PAIR_MARGIN_WEIGHT:-0.0}"
DECISION_SOURCE_PAIR_BALANCED_BCE="${DECISION_SOURCE_PAIR_BALANCED_BCE:-0}"
DECISION_SOURCE_PAIR_FOCAL_GAMMA="${DECISION_SOURCE_PAIR_FOCAL_GAMMA:-0.0}"
DECISION_SOURCE_PAIR_FOCAL_ALPHA="${DECISION_SOURCE_PAIR_FOCAL_ALPHA:-}"
SOURCE_GATE_SUPERVISION_WEIGHT="${SOURCE_GATE_SUPERVISION_WEIGHT:-0.0}"
SOURCE_GATE_BALANCED_BCE="${SOURCE_GATE_BALANCED_BCE:-0}"
SOURCE_GATE_CROP_REBALANCE_MAX_WEIGHT="${SOURCE_GATE_CROP_REBALANCE_MAX_WEIGHT:-4.0}"
SOURCE_GATE_FOCAL_GAMMA="${SOURCE_GATE_FOCAL_GAMMA:-0.0}"
SOURCE_GATE_FOCAL_ALPHA="${SOURCE_GATE_FOCAL_ALPHA:-}"
SOURCE_GATE_MARGIN_WEIGHT="${SOURCE_GATE_MARGIN_WEIGHT:-0.0}"
SOURCE_GATE_LOGIT_MARGIN="${SOURCE_GATE_LOGIT_MARGIN:-0.35}"
SOURCE_GATE_MARGIN_BALANCED="${SOURCE_GATE_MARGIN_BALANCED:-0}"
SOURCE_GATE_MARGIN_BALANCE_MAX_WEIGHT="${SOURCE_GATE_MARGIN_BALANCE_MAX_WEIGHT:-4.0}"
SOURCE_GATE_MARGIN_CROP_WEIGHT_MULT="${SOURCE_GATE_MARGIN_CROP_WEIGHT_MULT:-1.0}"
DELTA_WEIGHT="${DELTA_WEIGHT:-0.08}"
PROPOSAL_WEIGHT="${PROPOSAL_WEIGHT:-0.65}"
PROPOSAL_SUBJECT_WEIGHT="${PROPOSAL_SUBJECT_WEIGHT:-0.25}"
SUBJECT_PROPOSAL_ALIGN_WEIGHT="${SUBJECT_PROPOSAL_ALIGN_WEIGHT:-0.20}"
SUBJECT_BOX_WEIGHT="${SUBJECT_BOX_WEIGHT:-1.15}"
SUBJECT_BOX_VALID_WEIGHT="${SUBJECT_BOX_VALID_WEIGHT:-2.4}"
SUBJECT_BOX_L1_WEIGHT="${SUBJECT_BOX_L1_WEIGHT:-2.0}"
SUBJECT_BOX_IOU_WEIGHT="${SUBJECT_BOX_IOU_WEIGHT:-1.0}"
SUBJECT_BOX_CENTER_WEIGHT="${SUBJECT_BOX_CENTER_WEIGHT:-0.0}"
SUBJECT_BOX_SIZE_WEIGHT="${SUBJECT_BOX_SIZE_WEIGHT:-0.0}"
SUBJECT_BOX_ASPECT_WEIGHT="${SUBJECT_BOX_ASPECT_WEIGHT:-0.0}"
SUBJECT_BOX_CIOU_WEIGHT="${SUBJECT_BOX_CIOU_WEIGHT:-0.0}"
SUBJECT_BOX_VALID_NEGATIVE_SCALE="${SUBJECT_BOX_VALID_NEGATIVE_SCALE:-1.4}"
SUBJECT_BOX_SPATIAL_AUX_WEIGHT="${SUBJECT_BOX_SPATIAL_AUX_WEIGHT:-0.15}"
SUBJECT_BOX_SPATIAL_HEATMAP_WEIGHT="${SUBJECT_BOX_SPATIAL_HEATMAP_WEIGHT:-0.10}"
SUBJECT_BOX_SPATIAL_MASK_WEIGHT="${SUBJECT_BOX_SPATIAL_MASK_WEIGHT:-0.10}"
GENERATED_PROPOSAL_ALIGN_WEIGHT="${GENERATED_PROPOSAL_ALIGN_WEIGHT:-0.85}"
GENERATED_PROPOSAL_SCORE_WEIGHT="${GENERATED_PROPOSAL_SCORE_WEIGHT:-1.0}"
GENERATED_PROPOSAL_LISTWISE_WEIGHT="${GENERATED_PROPOSAL_LISTWISE_WEIGHT:-0.45}"
GENERATED_PROPOSAL_POSITIVE_WEIGHT="${GENERATED_PROPOSAL_POSITIVE_WEIGHT:-0.35}"
GENERATED_PROPOSAL_RISK_WEIGHT="${GENERATED_PROPOSAL_RISK_WEIGHT:-0.2}"
GENERATED_PROPOSAL_POSITIVE_UTILITY_WEIGHT="${GENERATED_PROPOSAL_POSITIVE_UTILITY_WEIGHT:-0.08}"
GENERATED_PROPOSAL_POSITIVE_MARGIN_WEIGHT="${GENERATED_PROPOSAL_POSITIVE_MARGIN_WEIGHT:-0.0}"
GENERATED_PROPOSAL_POSITIVE_MARGIN="${GENERATED_PROPOSAL_POSITIVE_MARGIN:-0.25}"
GENERATED_PROPOSAL_MATCH_IOU="${GENERATED_PROPOSAL_MATCH_IOU:-0.35}"
SELECTION_METRIC="${SELECTION_METRIC:-release_gate_joint}"
ENABLE_TRAIN_GATE="${ENABLE_TRAIN_GATE:-1}"
TRAIN_GATE_ROUTE_BALANCED_MIN="${TRAIN_GATE_ROUTE_BALANCED_MIN:-0.52}"
TRAIN_GATE_SUBJECT_IOU_MIN="${TRAIN_GATE_SUBJECT_IOU_MIN:-0.50}"
TRAIN_GATE_SUBJECT_VALID_BALANCED_MIN="${TRAIN_GATE_SUBJECT_VALID_BALANCED_MIN:-0.55}"
TRAIN_GATE_PROPOSAL_RECALL_MIN="${TRAIN_GATE_PROPOSAL_RECALL_MIN:-0.93}"
TRAIN_GATE_ACTION_TOP1_MIN="${TRAIN_GATE_ACTION_TOP1_MIN:-0.96}"
TRAIN_GATE_TOP_RETURN_MIN="${TRAIN_GATE_TOP_RETURN_MIN:-0.58}"
TRAIN_GATE_GENERATED_ALIGN_MIN="${TRAIN_GATE_GENERATED_ALIGN_MIN:-0.90}"
TRAIN_GATE_BASELINE_PRESERVE_MIN="${TRAIN_GATE_BASELINE_PRESERVE_MIN:-0.955}"
TRAIN_GATE_BASELINE_TARGET_RATE_MIN="${TRAIN_GATE_BASELINE_TARGET_RATE_MIN:-0.05}"
TRAIN_GATE_RAW_TOP_RETURN_MODE="${TRAIN_GATE_RAW_TOP_RETURN_MODE:-auto}"

cd "${ROOT}"
mkdir -p "${OUT_DIR}"

EMBED="artifacts/mobilecropnet_v4/quality_first_20260428/embedded_route_expert_checkpoints/${RUN_NAME}-swinroute-embedded.pt"
SUBJECT_VALID_THRESHOLD_TAG="${SUBJECT_VALID_THRESHOLD_TAG:-$(/usr/local/bin/python3 - <<PY
value = float(${SUBJECT_VALID_THRESHOLD@Q})
print(f"{int(round(value * 100)):03d}")
PY
)}"
GATE_TAG="${RUN_NAME}-swinembed-vthr${SUBJECT_VALID_THRESHOLD_TAG}"
STATUS="artifacts/mobilecropnet_v4/quality_first_20260428/gate_runs/${GATE_TAG}/status.json"
HEAD_OUT="artifacts/mobilecropnet_v4/quality_first_20260428/head_audits/${GATE_TAG}"
DIRECT_OUT="artifacts/mobilecropnet_v4/quality_first_20260428/direct_eval/${GATE_TAG}_sortfix"
QUAL_OUT="artifacts/mobilecropnet_v4/quality_first_20260428/qualitative/${GATE_TAG}_sortfix"
INIT_ARGS=()
if [[ -n "${INIT_CHECKPOINT}" ]]; then
  INIT_ARGS+=(--init_checkpoint "${INIT_CHECKPOINT}")
fi
if [[ -n "${INIT_CHECKPOINT_SKIP_PREFIXES}" ]]; then
  INIT_ARGS+=(--init_checkpoint_skip_prefixes "${INIT_CHECKPOINT_SKIP_PREFIXES}")
fi
TRAINABLE_ARGS=()
if [[ -n "${TRAINABLE_PREFIXES}" ]]; then
  TRAINABLE_ARGS+=(--trainable_module_prefixes "${TRAINABLE_PREFIXES}")
fi
ROUTE_IMAGE_RESIDUAL_ARGS=()
if [[ "${ROUTE_IMAGE_RESIDUAL,,}" =~ ^(1|true|yes|on)$ ]]; then
  ROUTE_IMAGE_RESIDUAL_ARGS+=(--route_image_residual)
fi
ROUTE_CONDITION_ARGS=()
if [[ "${ROUTE_CONDITION_CANDIDATE_SCORES,,}" =~ ^(1|true|yes|on)$ ]]; then
  ROUTE_CONDITION_ARGS+=(--route_condition_candidate_scores)
fi
if [[ "${ROUTE_CONDITION_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  ROUTE_CONDITION_ARGS+=(--no-route_condition_detach)
fi
RETURN_SCORE_ARGS=()
if [[ "${RETURN_SCORE_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_head)
fi
RETURN_SCORE_ARGS+=(--return_score_head_depth "${RETURN_SCORE_HEAD_DEPTH}")
RETURN_SCORE_ARGS+=(--return_score_head_hidden_mult "${RETURN_SCORE_HEAD_HIDDEN_MULT}")
if [[ "${RETURN_SCORE_ACTION_SOURCE_BIAS,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_action_source_bias)
fi
if [[ "${RETURN_SCORE_DECISION_SOURCE_BIAS,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_decision_source_bias)
fi
if [[ "${RETURN_SCORE_DECISION_SOURCE_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_decision_source_detach)
fi
RETURN_SCORE_ARGS+=(--return_score_decision_source_max_scale "${RETURN_SCORE_DECISION_SOURCE_MAX_SCALE}")
if [[ "${RETURN_SCORE_DECISION_SOURCE_FROM_SOURCE_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_decision_source_from_source_head)
fi
if [[ "${RETURN_SCORE_DECISION_CONDITIONED,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_decision_conditioned)
fi
RETURN_SCORE_ARGS+=(--return_score_decision_conditioned_mask_value "${RETURN_SCORE_DECISION_CONDITIONED_MASK_VALUE}")
if [[ "${RETURN_SCORE_DECISION_CONDITIONED_FROM_SOURCE_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_decision_conditioned_from_source_head)
fi
if [[ "${RETURN_SCORE_SOURCE_MIXTURE,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_source_mixture)
fi
RETURN_SCORE_ARGS+=(--return_score_source_mixture_strength "${RETURN_SCORE_SOURCE_MIXTURE_STRENGTH}")
if [[ "${RETURN_SCORE_SOURCE_MIXTURE_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_source_mixture_detach)
fi
if [[ "${RETURN_SCORE_SOURCE_MIXTURE_FROM_SOURCE_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_source_mixture_from_source_head)
fi
if [[ -n "${RETURN_SCORE_SOURCE_MIXTURE_GAP_THRESHOLD}" ]]; then
  RETURN_SCORE_ARGS+=(--return_score_source_mixture_gap_threshold "${RETURN_SCORE_SOURCE_MIXTURE_GAP_THRESHOLD}")
fi
RETURN_SCORE_ARGS+=(--return_score_source_mixture_gap_mask_value "${RETURN_SCORE_SOURCE_MIXTURE_GAP_MASK_VALUE}")
if [[ "${RETURN_SCORE_SOURCE_GATE,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_source_gate)
fi
RETURN_SCORE_ARGS+=(--return_score_source_gate_hidden_mult "${RETURN_SCORE_SOURCE_GATE_HIDDEN_MULT}")
RETURN_SCORE_ARGS+=(--return_score_source_gate_strength "${RETURN_SCORE_SOURCE_GATE_STRENGTH}")
RETURN_SCORE_ARGS+=(--return_score_source_gate_logit_threshold "${RETURN_SCORE_SOURCE_GATE_LOGIT_THRESHOLD}")
if [[ "${RETURN_SCORE_SOURCE_GATE_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_source_gate_detach)
fi
if [[ "${RETURN_SCORE_SOURCE_GATE_SUBJECT_STATE,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_source_gate_subject_state)
fi
if [[ "${RETURN_SCORE_SOURCE_GATE_SUBJECT_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_source_gate_subject_detach)
fi
if [[ "${RETURN_SCORE_SOURCE_SPECIFIC_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_source_specific_head)
fi
RETURN_SCORE_ARGS+=(--return_score_source_specific_hidden_mult "${RETURN_SCORE_SOURCE_SPECIFIC_HIDDEN_MULT}")
if [[ "${RETURN_SCORE_CONTEXT_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_context_head)
fi
RETURN_SCORE_ARGS+=(--return_score_context_hidden_mult "${RETURN_SCORE_CONTEXT_HIDDEN_MULT}")
if [[ "${RETURN_SCORE_CONTEXT_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_context_detach)
fi
if [[ "${RETURN_SCORE_POLICY_MATCH_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_policy_match_head)
fi
RETURN_SCORE_ARGS+=(--return_score_policy_match_hidden_mult "${RETURN_SCORE_POLICY_MATCH_HIDDEN_MULT}")
if [[ "${RETURN_SCORE_POLICY_MATCH_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_policy_match_detach)
fi
if [[ "${RETURN_SCORE_POLICY_SOURCE_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_policy_source_head)
fi
RETURN_SCORE_ARGS+=(--return_score_policy_source_hidden_mult "${RETURN_SCORE_POLICY_SOURCE_HIDDEN_MULT}")
if [[ "${RETURN_SCORE_POLICY_SOURCE_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_policy_source_detach)
fi
if [[ "${RETURN_SCORE_COMPETITION_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_competition_head)
fi
RETURN_SCORE_ARGS+=(--return_score_competition_hidden_mult "${RETURN_SCORE_COMPETITION_HIDDEN_MULT}")
if [[ "${RETURN_SCORE_COMPETITION_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_competition_detach)
fi
if [[ "${RETURN_SCORE_SET_REFINER_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_set_refiner_head)
fi
RETURN_SCORE_ARGS+=(--return_score_set_refiner_hidden_mult "${RETURN_SCORE_SET_REFINER_HIDDEN_MULT}")
RETURN_SCORE_ARGS+=(--return_score_set_refiner_layers "${RETURN_SCORE_SET_REFINER_LAYERS}")
if [[ "${RETURN_SCORE_SET_REFINER_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_set_refiner_detach)
fi
if [[ "${RETURN_SCORE_ACTION_DECODER_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_action_decoder_head)
fi
RETURN_SCORE_ARGS+=(--return_score_action_decoder_hidden_mult "${RETURN_SCORE_ACTION_DECODER_HIDDEN_MULT}")
RETURN_SCORE_ARGS+=(--return_score_action_decoder_layers "${RETURN_SCORE_ACTION_DECODER_LAYERS}")
if [[ "${RETURN_SCORE_ACTION_DECODER_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_action_decoder_detach)
fi
if [[ "${RETURN_SCORE_ACTION_DECODER_SUBJECT_STATE,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_action_decoder_subject_state)
fi
if [[ "${RETURN_SCORE_ACTION_DECODER_SUBJECT_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  RETURN_SCORE_ARGS+=(--no-return_score_action_decoder_subject_detach)
fi
if [[ "${RETURN_SCORE_ACTION_DECODER_REPLACE,,}" =~ ^(1|true|yes|on)$ ]]; then
  RETURN_SCORE_ARGS+=(--return_score_action_decoder_replace)
fi
SUBJECT_BOX_ARGS=()
if [[ "${SUBJECT_BOX_REFINE_WITH_PROPOSALS,,}" =~ ^(1|true|yes|on)$ ]]; then
  SUBJECT_BOX_ARGS+=(--subject_box_refine_with_proposals)
fi
if [[ "${SUBJECT_VALID_ROUTE_CALIBRATOR,,}" =~ ^(1|true|yes|on)$ ]]; then
  SUBJECT_BOX_ARGS+=(--subject_valid_route_calibrator)
fi
SUBJECT_BOX_ARGS+=(--subject_valid_route_calibrator_hidden_mult "${SUBJECT_VALID_ROUTE_CALIBRATOR_HIDDEN_MULT}")
if [[ "${SUBJECT_VALID_ROUTE_CALIBRATOR_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  SUBJECT_BOX_ARGS+=(--no-subject_valid_route_calibrator_detach)
fi
DECISION_ARGS=()
if [[ "${DECISION_SOURCE_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--decision_source_head)
fi
DECISION_ARGS+=(--decision_source_logit_threshold "${DECISION_SOURCE_LOGIT_THRESHOLD}")
if [[ "${DECISION_SOURCE_PAIR_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--decision_source_pair_head)
fi
DECISION_ARGS+=(--decision_source_pair_hidden_mult "${DECISION_SOURCE_PAIR_HIDDEN_MULT}")
if [[ "${DECISION_SOURCE_PAIR_AFTER_RETURN_DELTAS,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--decision_source_pair_after_return_deltas)
fi
if [[ "${DECISION_SOURCE_PAIR_SUBJECT_STATE,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--decision_source_pair_subject_state)
fi
if [[ "${DECISION_SOURCE_PAIR_SUBJECT_DETACH,,}" =~ ^(0|false|no|off)$ ]]; then
  DECISION_ARGS+=(--no-decision_source_pair_subject_detach)
fi
if [[ "${DECISION_CROP_REBALANCE,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--decision_crop_rebalance)
fi
DECISION_ARGS+=(--decision_crop_rebalance_max_weight "${DECISION_CROP_REBALANCE_MAX_WEIGHT}")
if [[ "${DECISION_SOURCE_BALANCED_BCE,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--decision_source_balanced_bce)
fi
DECISION_ARGS+=(--decision_source_weight "${DECISION_SOURCE_WEIGHT}")
DECISION_ARGS+=(--decision_source_crop_rebalance_max_weight "${DECISION_SOURCE_CROP_REBALANCE_MAX_WEIGHT}")
DECISION_ARGS+=(--decision_source_focal_gamma "${DECISION_SOURCE_FOCAL_GAMMA}")
if [[ -n "${DECISION_SOURCE_FOCAL_ALPHA}" ]]; then
  DECISION_ARGS+=(--decision_source_focal_alpha "${DECISION_SOURCE_FOCAL_ALPHA}")
fi
if [[ "${DECISION_SOURCE_PAIR_BALANCED_BCE,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--decision_source_pair_balanced_bce)
fi
DECISION_ARGS+=(--decision_source_pair_supervision_weight "${DECISION_SOURCE_PAIR_SUPERVISION_WEIGHT}")
DECISION_ARGS+=(--decision_source_pair_margin_weight "${DECISION_SOURCE_PAIR_MARGIN_WEIGHT}")
DECISION_ARGS+=(--decision_source_pair_focal_gamma "${DECISION_SOURCE_PAIR_FOCAL_GAMMA}")
if [[ -n "${DECISION_SOURCE_PAIR_FOCAL_ALPHA}" ]]; then
  DECISION_ARGS+=(--decision_source_pair_focal_alpha "${DECISION_SOURCE_PAIR_FOCAL_ALPHA}")
fi
DECISION_ARGS+=(--source_gate_supervision_weight "${SOURCE_GATE_SUPERVISION_WEIGHT}")
if [[ "${SOURCE_GATE_BALANCED_BCE,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--source_gate_balanced_bce)
fi
DECISION_ARGS+=(--source_gate_crop_rebalance_max_weight "${SOURCE_GATE_CROP_REBALANCE_MAX_WEIGHT}")
DECISION_ARGS+=(--source_gate_focal_gamma "${SOURCE_GATE_FOCAL_GAMMA}")
if [[ -n "${SOURCE_GATE_FOCAL_ALPHA}" ]]; then
  DECISION_ARGS+=(--source_gate_focal_alpha "${SOURCE_GATE_FOCAL_ALPHA}")
fi
DECISION_ARGS+=(--source_gate_margin_weight "${SOURCE_GATE_MARGIN_WEIGHT}")
DECISION_ARGS+=(--source_gate_logit_margin "${SOURCE_GATE_LOGIT_MARGIN}")
if [[ "${SOURCE_GATE_MARGIN_BALANCED,,}" =~ ^(1|true|yes|on)$ ]]; then
  DECISION_ARGS+=(--source_gate_margin_balanced)
fi
DECISION_ARGS+=(--source_gate_margin_balance_max_weight "${SOURCE_GATE_MARGIN_BALANCE_MAX_WEIGHT}")
DECISION_ARGS+=(--source_gate_margin_crop_weight_mult "${SOURCE_GATE_MARGIN_CROP_WEIGHT_MULT}")
ACTION_SOURCE_ARGS=()
if [[ "${ACTION_SOURCE_BALANCED,,}" =~ ^(1|true|yes|on)$ ]]; then
  ACTION_SOURCE_ARGS+=(--action_source_balanced)
fi
ACTION_SOURCE_ARGS+=(--action_source_balance_max_weight "${ACTION_SOURCE_BALANCE_MAX_WEIGHT}")
ACTION_SOURCE_ARGS+=(--action_source_crop_weight_mult "${ACTION_SOURCE_CROP_WEIGHT_MULT}")
BACKBONE_PRETRAINED_ARGS=()
BACKBONE_PRETRAINED_NORM="${BACKBONE_PRETRAINED,,}"
if [[ "${BACKBONE_PRETRAINED_NORM}" == "auto" ]]; then
  if [[ -n "${INIT_CHECKPOINT}" ]]; then
    INIT_SKIP_COMPACT=",${INIT_CHECKPOINT_SKIP_PREFIXES//[[:space:]]/,},"
    if [[ "${INIT_SKIP_COMPACT}" == *",backbone,"* ]]; then
      BACKBONE_PRETRAINED_ARGS+=(--backbone_pretrained)
    else
      BACKBONE_PRETRAINED_ARGS+=(--no-backbone_pretrained)
    fi
  fi
elif [[ "${BACKBONE_PRETRAINED_NORM}" =~ ^(0|false|no|off)$ ]]; then
  BACKBONE_PRETRAINED_ARGS+=(--no-backbone_pretrained)
elif [[ "${BACKBONE_PRETRAINED_NORM}" =~ ^(1|true|yes|on)$ ]]; then
  BACKBONE_PRETRAINED_ARGS+=(--backbone_pretrained)
else
  echo "invalid BACKBONE_PRETRAINED=${BACKBONE_PRETRAINED}; expected auto/0/1" >&2
  exit 2
fi
MODEL_OVERRIDE_ARGS=()
if [[ -n "${INPUT_SIZE}" ]]; then
  MODEL_OVERRIDE_ARGS+=(--input_size "${INPUT_SIZE}")
fi
if [[ -n "${CANDIDATE_K}" ]]; then
  MODEL_OVERRIDE_ARGS+=(--candidate_k "${CANDIDATE_K}")
fi
if [[ -n "${PROPOSAL_Q}" ]]; then
  MODEL_OVERRIDE_ARGS+=(--proposal_q "${PROPOSAL_Q}")
fi
if [[ -n "${TOKEN_DIM}" ]]; then
  MODEL_OVERRIDE_ARGS+=(--token_dim "${TOKEN_DIM}")
fi
if [[ -n "${BACKBONE_NAME}" ]]; then
  MODEL_OVERRIDE_ARGS+=(--backbone_name "${BACKBONE_NAME}")
fi
if [[ -n "${IMAGE_MEAN}" ]]; then
  MODEL_OVERRIDE_ARGS+=(--image_mean "${IMAGE_MEAN}")
fi
if [[ -n "${IMAGE_STD}" ]]; then
  MODEL_OVERRIDE_ARGS+=(--image_std "${IMAGE_STD}")
fi
PAIRWISE_ARGS=(--max_pairwise_pairs "${MAX_PAIRWISE_PAIRS}")
if [[ -n "${PAIRWISE_JSONL}" ]]; then
  PAIRWISE_ARGS+=(--pairwise_jsonl "${PAIRWISE_JSONL}")
fi
if [[ -n "${VAL_PAIRWISE_JSONL}" ]]; then
  PAIRWISE_ARGS+=(--val_pairwise_jsonl "${VAL_PAIRWISE_JSONL}")
fi

/usr/local/bin/python3 - <<PY
import json
from pathlib import Path

payload = {
    "run_name": ${RUN_NAME@Q},
    "out_dir": ${OUT_DIR@Q},
    "model_profile": ${MODEL_PROFILE@Q},
    "input_size_override": ${INPUT_SIZE@Q},
    "candidate_k_override": ${CANDIDATE_K@Q},
    "proposal_q_override": ${PROPOSAL_Q@Q},
    "token_dim_override": ${TOKEN_DIM@Q},
    "backbone_name_override": ${BACKBONE_NAME@Q},
    "image_mean_override": ${IMAGE_MEAN@Q},
    "image_std_override": ${IMAGE_STD@Q},
    "train_jsonl": ${TRAIN_JSONL@Q},
    "val_jsonl": ${VAL_JSONL@Q},
    "pairwise_jsonl": ${PAIRWISE_JSONL@Q},
    "val_pairwise_jsonl": ${VAL_PAIRWISE_JSONL@Q},
    "max_pairwise_pairs": ${MAX_PAIRWISE_PAIRS@Q},
    "eval_jsonl": ${EVAL_JSONL@Q},
    "init_checkpoint": ${INIT_CHECKPOINT@Q},
    "init_checkpoint_skip_prefixes": ${INIT_CHECKPOINT_SKIP_PREFIXES@Q},
    "trainable_prefixes": ${TRAINABLE_PREFIXES@Q},
    "backbone_pretrained": ${BACKBONE_PRETRAINED@Q},
    "epochs": ${EPOCHS@Q},
    "batch_size": ${BATCH_SIZE@Q},
    "lr": ${LR@Q},
    "max_train_rows": ${MAX_TRAIN_ROWS@Q},
    "max_val_rows": ${MAX_VAL_ROWS@Q},
    "route_experts": [${ROUTE1@Q}, ${ROUTE2@Q}, ${ROUTE3@Q}],
    "route_expert_distill_weights": ${ROUTE_EXPERT_DISTILL_WEIGHTS@Q},
    "teacher_distill_weight": ${TEACHER_DISTILL_WEIGHT@Q},
    "topk_coverage_weight": ${TOPK_COVERAGE_WEIGHT@Q},
    "topk_coverage_k": ${TOPK_COVERAGE_K@Q},
    "action_consistency_margin": ${ACTION_CONSISTENCY_MARGIN@Q},
    "action_source_balanced": ${ACTION_SOURCE_BALANCED@Q},
    "action_source_balance_max_weight": ${ACTION_SOURCE_BALANCE_MAX_WEIGHT@Q},
    "action_source_crop_weight_mult": ${ACTION_SOURCE_CROP_WEIGHT_MULT@Q},
    "action_return_joint_weight": ${ACTION_RETURN_JOINT_WEIGHT@Q},
    "action_return_joint_score_margin": ${ACTION_RETURN_JOINT_SCORE_MARGIN@Q},
    "action_return_joint_logit_margin": ${ACTION_RETURN_JOINT_LOGIT_MARGIN@Q},
    "action_return_joint_temperature": ${ACTION_RETURN_JOINT_TEMPERATURE@Q},
    "return_source_margin_weight": ${RETURN_SOURCE_MARGIN_WEIGHT@Q},
    "return_source_margin_logit_margin": ${RETURN_SOURCE_MARGIN_LOGIT_MARGIN@Q},
    "return_source_margin_balanced": ${RETURN_SOURCE_MARGIN_BALANCED@Q},
    "return_source_margin_balance_max_weight": ${RETURN_SOURCE_MARGIN_BALANCE_MAX_WEIGHT@Q},
    "return_source_margin_crop_weight_mult": ${RETURN_SOURCE_MARGIN_CROP_WEIGHT_MULT@Q},
    "decision_source_logit_threshold": ${DECISION_SOURCE_LOGIT_THRESHOLD@Q},
    "decision_source_focal_gamma": ${DECISION_SOURCE_FOCAL_GAMMA@Q},
    "decision_source_focal_alpha": ${DECISION_SOURCE_FOCAL_ALPHA@Q},
    "decision_source_pair_head": ${DECISION_SOURCE_PAIR_HEAD@Q},
    "decision_source_pair_hidden_mult": ${DECISION_SOURCE_PAIR_HIDDEN_MULT@Q},
    "decision_source_pair_after_return_deltas": ${DECISION_SOURCE_PAIR_AFTER_RETURN_DELTAS@Q},
    "decision_source_pair_subject_state": ${DECISION_SOURCE_PAIR_SUBJECT_STATE@Q},
    "decision_source_pair_subject_detach": ${DECISION_SOURCE_PAIR_SUBJECT_DETACH@Q},
    "decision_source_margin_weight": ${DECISION_SOURCE_MARGIN_WEIGHT@Q},
    "decision_source_logit_margin": ${DECISION_SOURCE_LOGIT_MARGIN@Q},
    "decision_source_margin_balanced": ${DECISION_SOURCE_MARGIN_BALANCED@Q},
    "decision_source_margin_balance_max_weight": ${DECISION_SOURCE_MARGIN_BALANCE_MAX_WEIGHT@Q},
    "decision_source_margin_crop_weight_mult": ${DECISION_SOURCE_MARGIN_CROP_WEIGHT_MULT@Q},
    "decision_source_pair_supervision_weight": ${DECISION_SOURCE_PAIR_SUPERVISION_WEIGHT@Q},
    "decision_source_pair_margin_weight": ${DECISION_SOURCE_PAIR_MARGIN_WEIGHT@Q},
    "decision_source_pair_balanced_bce": ${DECISION_SOURCE_PAIR_BALANCED_BCE@Q},
    "decision_source_pair_focal_gamma": ${DECISION_SOURCE_PAIR_FOCAL_GAMMA@Q},
    "decision_source_pair_focal_alpha": ${DECISION_SOURCE_PAIR_FOCAL_ALPHA@Q},
    "source_gate_supervision_weight": ${SOURCE_GATE_SUPERVISION_WEIGHT@Q},
    "source_gate_balanced_bce": ${SOURCE_GATE_BALANCED_BCE@Q},
    "source_gate_crop_rebalance_max_weight": ${SOURCE_GATE_CROP_REBALANCE_MAX_WEIGHT@Q},
    "source_gate_focal_gamma": ${SOURCE_GATE_FOCAL_GAMMA@Q},
    "source_gate_focal_alpha": ${SOURCE_GATE_FOCAL_ALPHA@Q},
    "source_gate_margin_weight": ${SOURCE_GATE_MARGIN_WEIGHT@Q},
    "source_gate_logit_margin": ${SOURCE_GATE_LOGIT_MARGIN@Q},
    "source_gate_margin_balanced": ${SOURCE_GATE_MARGIN_BALANCED@Q},
    "source_gate_margin_balance_max_weight": ${SOURCE_GATE_MARGIN_BALANCE_MAX_WEIGHT@Q},
    "source_gate_margin_crop_weight_mult": ${SOURCE_GATE_MARGIN_CROP_WEIGHT_MULT@Q},
    "route_focal_gamma": ${ROUTE_FOCAL_GAMMA@Q},
    "route_image_residual": ${ROUTE_IMAGE_RESIDUAL@Q},
    "route_image_residual_weight": ${ROUTE_IMAGE_RESIDUAL_WEIGHT@Q},
    "route_condition_candidate_scores": ${ROUTE_CONDITION_CANDIDATE_SCORES@Q},
    "route_condition_detach": ${ROUTE_CONDITION_DETACH@Q},
    "return_score_head": ${RETURN_SCORE_HEAD@Q},
    "return_score_head_depth": ${RETURN_SCORE_HEAD_DEPTH@Q},
    "return_score_head_hidden_mult": ${RETURN_SCORE_HEAD_HIDDEN_MULT@Q},
    "return_score_action_source_bias": ${RETURN_SCORE_ACTION_SOURCE_BIAS@Q},
    "return_score_decision_source_bias": ${RETURN_SCORE_DECISION_SOURCE_BIAS@Q},
    "return_score_decision_source_detach": ${RETURN_SCORE_DECISION_SOURCE_DETACH@Q},
    "return_score_decision_source_max_scale": ${RETURN_SCORE_DECISION_SOURCE_MAX_SCALE@Q},
    "return_score_decision_source_from_source_head": ${RETURN_SCORE_DECISION_SOURCE_FROM_SOURCE_HEAD@Q},
    "return_score_decision_conditioned": ${RETURN_SCORE_DECISION_CONDITIONED@Q},
    "return_score_decision_conditioned_mask_value": ${RETURN_SCORE_DECISION_CONDITIONED_MASK_VALUE@Q},
    "return_score_decision_conditioned_from_source_head": ${RETURN_SCORE_DECISION_CONDITIONED_FROM_SOURCE_HEAD@Q},
    "return_score_source_mixture": ${RETURN_SCORE_SOURCE_MIXTURE@Q},
    "return_score_source_mixture_strength": ${RETURN_SCORE_SOURCE_MIXTURE_STRENGTH@Q},
    "return_score_source_mixture_detach": ${RETURN_SCORE_SOURCE_MIXTURE_DETACH@Q},
    "return_score_source_mixture_from_source_head": ${RETURN_SCORE_SOURCE_MIXTURE_FROM_SOURCE_HEAD@Q},
    "return_score_source_mixture_gap_threshold": ${RETURN_SCORE_SOURCE_MIXTURE_GAP_THRESHOLD@Q},
    "return_score_source_mixture_gap_mask_value": ${RETURN_SCORE_SOURCE_MIXTURE_GAP_MASK_VALUE@Q},
    "return_score_source_gate": ${RETURN_SCORE_SOURCE_GATE@Q},
    "return_score_source_gate_hidden_mult": ${RETURN_SCORE_SOURCE_GATE_HIDDEN_MULT@Q},
    "return_score_source_gate_strength": ${RETURN_SCORE_SOURCE_GATE_STRENGTH@Q},
    "return_score_source_gate_detach": ${RETURN_SCORE_SOURCE_GATE_DETACH@Q},
    "return_score_source_gate_subject_state": ${RETURN_SCORE_SOURCE_GATE_SUBJECT_STATE@Q},
    "return_score_source_gate_subject_detach": ${RETURN_SCORE_SOURCE_GATE_SUBJECT_DETACH@Q},
    "return_score_source_gate_logit_threshold": ${RETURN_SCORE_SOURCE_GATE_LOGIT_THRESHOLD@Q},
    "return_score_source_specific_head": ${RETURN_SCORE_SOURCE_SPECIFIC_HEAD@Q},
    "return_score_source_specific_hidden_mult": ${RETURN_SCORE_SOURCE_SPECIFIC_HIDDEN_MULT@Q},
    "return_score_context_head": ${RETURN_SCORE_CONTEXT_HEAD@Q},
    "return_score_context_hidden_mult": ${RETURN_SCORE_CONTEXT_HIDDEN_MULT@Q},
    "return_score_context_detach": ${RETURN_SCORE_CONTEXT_DETACH@Q},
    "return_score_policy_match_head": ${RETURN_SCORE_POLICY_MATCH_HEAD@Q},
    "return_score_policy_match_hidden_mult": ${RETURN_SCORE_POLICY_MATCH_HIDDEN_MULT@Q},
    "return_score_policy_match_detach": ${RETURN_SCORE_POLICY_MATCH_DETACH@Q},
    "return_score_policy_source_head": ${RETURN_SCORE_POLICY_SOURCE_HEAD@Q},
    "return_score_policy_source_hidden_mult": ${RETURN_SCORE_POLICY_SOURCE_HIDDEN_MULT@Q},
    "return_score_policy_source_detach": ${RETURN_SCORE_POLICY_SOURCE_DETACH@Q},
    "return_score_competition_head": ${RETURN_SCORE_COMPETITION_HEAD@Q},
    "return_score_competition_hidden_mult": ${RETURN_SCORE_COMPETITION_HIDDEN_MULT@Q},
    "return_score_competition_detach": ${RETURN_SCORE_COMPETITION_DETACH@Q},
    "return_score_set_refiner_head": ${RETURN_SCORE_SET_REFINER_HEAD@Q},
    "return_score_set_refiner_hidden_mult": ${RETURN_SCORE_SET_REFINER_HIDDEN_MULT@Q},
    "return_score_set_refiner_layers": ${RETURN_SCORE_SET_REFINER_LAYERS@Q},
    "return_score_set_refiner_detach": ${RETURN_SCORE_SET_REFINER_DETACH@Q},
    "return_score_action_decoder_head": ${RETURN_SCORE_ACTION_DECODER_HEAD@Q},
    "return_score_action_decoder_hidden_mult": ${RETURN_SCORE_ACTION_DECODER_HIDDEN_MULT@Q},
    "return_score_action_decoder_layers": ${RETURN_SCORE_ACTION_DECODER_LAYERS@Q},
    "return_score_action_decoder_detach": ${RETURN_SCORE_ACTION_DECODER_DETACH@Q},
    "return_score_action_decoder_subject_state": ${RETURN_SCORE_ACTION_DECODER_SUBJECT_STATE@Q},
    "return_score_action_decoder_subject_detach": ${RETURN_SCORE_ACTION_DECODER_SUBJECT_DETACH@Q},
    "return_score_action_decoder_replace": ${RETURN_SCORE_ACTION_DECODER_REPLACE@Q},
    "subject_box_valid_target_mode": ${SUBJECT_BOX_VALID_TARGET_MODE@Q},
    "subject_box_valid_reliability_min": ${SUBJECT_BOX_VALID_RELIABILITY_MIN@Q},
    "subject_box_refine_with_proposals": ${SUBJECT_BOX_REFINE_WITH_PROPOSALS@Q},
    "subject_valid_route_calibrator": ${SUBJECT_VALID_ROUTE_CALIBRATOR@Q},
    "subject_valid_route_calibrator_hidden_mult": ${SUBJECT_VALID_ROUTE_CALIBRATOR_HIDDEN_MULT@Q},
    "subject_valid_route_calibrator_detach": ${SUBJECT_VALID_ROUTE_CALIBRATOR_DETACH@Q},
    "raw_top_return_weight": ${RAW_TOP_RETURN_WEIGHT@Q},
    "return_score_weight": ${RETURN_SCORE_WEIGHT@Q},
    "return_listwise_weight": ${RETURN_LISTWISE_WEIGHT@Q},
    "return_positive_weight": ${RETURN_POSITIVE_WEIGHT@Q},
    "return_positive_margin_weight": ${RETURN_POSITIVE_MARGIN_WEIGHT@Q},
    "return_positive_margin": ${RETURN_POSITIVE_MARGIN@Q},
    "return_risk_suppression_weight": ${RETURN_RISK_SUPPRESSION_WEIGHT@Q},
    "return_risk_suppression_margin": ${RETURN_RISK_SUPPRESSION_MARGIN@Q},
    "return_exact_weight": ${RETURN_EXACT_WEIGHT@Q},
    "return_exact_min_gap": ${RETURN_EXACT_MIN_GAP@Q},
    "return_target_mode": ${RETURN_TARGET_MODE@Q},
    "return_explicit_pairwise_weight": ${RETURN_EXPLICIT_PAIRWISE_WEIGHT@Q},
    "return_explicit_pairwise_margin": ${RETURN_EXPLICIT_PAIRWISE_MARGIN@Q},
    "route_object_single_margin_weight": ${ROUTE_OBJECT_SINGLE_MARGIN_WEIGHT@Q},
    "train_route_balanced_sampler_power": ${TRAIN_ROUTE_BALANCED_SAMPLER_POWER@Q},
    "train_decision_source_balanced_sampler": ${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER@Q},
    "train_decision_source_balanced_sampler_power": ${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_POWER@Q},
    "train_decision_source_balanced_sampler_min_weight": ${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_MIN_WEIGHT@Q},
    "train_decision_source_balanced_sampler_max_weight": ${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_MAX_WEIGHT@Q},
    "decision_source_head": ${DECISION_SOURCE_HEAD@Q},
    "decision_source_weight": ${DECISION_SOURCE_WEIGHT@Q},
    "decision_source_balanced_bce": ${DECISION_SOURCE_BALANCED_BCE@Q},
    "decision_source_crop_rebalance_max_weight": ${DECISION_SOURCE_CROP_REBALANCE_MAX_WEIGHT@Q},
    "decision_source_focal_gamma": ${DECISION_SOURCE_FOCAL_GAMMA@Q},
    "decision_source_focal_alpha": ${DECISION_SOURCE_FOCAL_ALPHA@Q},
    "decision_source_pair_focal_gamma": ${DECISION_SOURCE_PAIR_FOCAL_GAMMA@Q},
    "decision_source_pair_focal_alpha": ${DECISION_SOURCE_PAIR_FOCAL_ALPHA@Q},
    "source_gate_supervision_weight": ${SOURCE_GATE_SUPERVISION_WEIGHT@Q},
    "source_gate_balanced_bce": ${SOURCE_GATE_BALANCED_BCE@Q},
    "source_gate_crop_rebalance_max_weight": ${SOURCE_GATE_CROP_REBALANCE_MAX_WEIGHT@Q},
    "source_gate_focal_gamma": ${SOURCE_GATE_FOCAL_GAMMA@Q},
    "source_gate_focal_alpha": ${SOURCE_GATE_FOCAL_ALPHA@Q},
    "source_gate_margin_weight": ${SOURCE_GATE_MARGIN_WEIGHT@Q},
    "source_gate_logit_margin": ${SOURCE_GATE_LOGIT_MARGIN@Q},
    "source_gate_margin_balanced": ${SOURCE_GATE_MARGIN_BALANCED@Q},
    "source_gate_margin_balance_max_weight": ${SOURCE_GATE_MARGIN_BALANCE_MAX_WEIGHT@Q},
    "source_gate_margin_crop_weight_mult": ${SOURCE_GATE_MARGIN_CROP_WEIGHT_MULT@Q},
    "decision_crop_rebalance": ${DECISION_CROP_REBALANCE@Q},
    "decision_crop_rebalance_max_weight": ${DECISION_CROP_REBALANCE_MAX_WEIGHT@Q},
    "subject_box_weight": ${SUBJECT_BOX_WEIGHT@Q},
    "subject_box_l1_weight": ${SUBJECT_BOX_L1_WEIGHT@Q},
    "subject_box_iou_weight": ${SUBJECT_BOX_IOU_WEIGHT@Q},
    "generated_proposal_positive_margin_weight": ${GENERATED_PROPOSAL_POSITIVE_MARGIN_WEIGHT@Q},
    "train_gate_baseline_preserve_min": ${TRAIN_GATE_BASELINE_PRESERVE_MIN@Q},
    "train_gate_baseline_target_rate_min": ${TRAIN_GATE_BASELINE_TARGET_RATE_MIN@Q},
    "train_gate_raw_top_return_mode": ${TRAIN_GATE_RAW_TOP_RETURN_MODE@Q},
    "embedded_checkpoint": ${EMBED@Q},
    "gate_status": ${STATUS@Q},
}
Path(${OUT_DIR@Q}, "quality_relaxed_joint_launch_config.json").write_text(
    json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)
PY

{
  date -u +"start_utc=%Y-%m-%dT%H:%M:%SZ"
  nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader
  /usr/local/bin/python3 - <<'PY'
import torch
print("torch_version", torch.__version__)
print("cuda_available", torch.cuda.is_available())
assert torch.cuda.is_available()
print("device_name", torch.cuda.get_device_name(0))
PY
} | tee "${OUT_DIR}/environment.log"

/usr/local/bin/python3 src/scripts/train_mobilecropnet_v4.py \
  --train_jsonl "${TRAIN_JSONL}" \
  --val_jsonl "${VAL_JSONL}" \
  --project_root . \
  --output_dir "${OUT_DIR}" \
  --model_profile "${MODEL_PROFILE}" \
  "${MODEL_OVERRIDE_ARGS[@]}" \
  "${BACKBONE_PRETRAINED_ARGS[@]}" \
  --use_subject_prior \
  --route_use_subject_prior \
  --route_use_candidate_context \
  --route_use_subject_box_features \
  --route_aux_heads \
  --route_head_depth "${ROUTE_HEAD_DEPTH}" \
  --route_head_hidden_mult "${ROUTE_HEAD_HIDDEN_MULT}" \
  "${ROUTE_IMAGE_RESIDUAL_ARGS[@]}" \
  --route_image_residual_weight "${ROUTE_IMAGE_RESIDUAL_WEIGHT}" \
  --route_decode_mode "${ROUTE_DECODE_MODE}" \
  "${ROUTE_CONDITION_ARGS[@]}" \
  "${RETURN_SCORE_ARGS[@]}" \
  --policy_use_subject_prior \
  --proposal_use_subject_prior \
  --subject_box_head \
  --subject_box_spatial_head \
  --subject_box_spatial_multiscale \
  "${SUBJECT_BOX_ARGS[@]}" \
  --subject_box_spatial_output spatial \
  --subject_box_spatial_box_mode mask_moment_regress \
  --subject_box_coord_space content \
  --use_pred_subject_box_as_prior \
  --detach_pred_subject_prior \
  --policy_score_head \
  --epochs "${EPOCHS}" \
  --batch_size "${BATCH_SIZE}" \
  --lr "${LR}" \
  --min_lr "${MIN_LR}" \
  --warmup_epochs "${WARMUP_EPOCHS}" \
  --weight_decay "${WEIGHT_DECAY}" \
  --num_workers "${NUM_WORKERS}" \
  --amp \
  "${INIT_ARGS[@]}" \
  "${TRAINABLE_ARGS[@]}" \
  "${PAIRWISE_ARGS[@]}" \
  --train_route_balanced_sampler \
  --train_route_balanced_sampler_power "${TRAIN_ROUTE_BALANCED_SAMPLER_POWER}" \
  --train_route_balanced_sampler_min_weight "${TRAIN_ROUTE_BALANCED_SAMPLER_MIN_WEIGHT}" \
  --train_route_balanced_sampler_max_weight "${TRAIN_ROUTE_BALANCED_SAMPLER_MAX_WEIGHT}" \
  $([[ "${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER,,}" =~ ^(1|true|yes|on)$ ]] && printf '%s' '--train_decision_source_balanced_sampler') \
  --train_decision_source_balanced_sampler_power "${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_POWER}" \
  --train_decision_source_balanced_sampler_min_weight "${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_MIN_WEIGHT}" \
  --train_decision_source_balanced_sampler_max_weight "${TRAIN_DECISION_SOURCE_BALANCED_SAMPLER_MAX_WEIGHT}" \
  --max_train_rows "${MAX_TRAIN_ROWS}" \
  --max_val_rows "${MAX_VAL_ROWS}" \
  --score_target_mode hybrid_rank \
  --subject_box_target_source "${SUBJECT_BOX_TARGET_SOURCE}" \
  --subject_box_valid_target_mode "${SUBJECT_BOX_VALID_TARGET_MODE}" \
  --subject_box_valid_reliability_min "${SUBJECT_BOX_VALID_RELIABILITY_MIN}" \
  --score_weight "${SCORE_WEIGHT}" \
  --listwise_weight "${LISTWISE_WEIGHT}" \
  --pairwise_weight "${PAIRWISE_WEIGHT}" \
  --explicit_pairwise_weight "${EXPLICIT_PAIRWISE_WEIGHT}" \
  --positive_weight "${POSITIVE_WEIGHT}" \
  --risk_weight "${RISK_WEIGHT}" \
  --top1_risk_weight "${TOP1_RISK_WEIGHT}" \
  --top_return_weight "${TOP_RETURN_WEIGHT}" \
  --raw_top_return_weight "${RAW_TOP_RETURN_WEIGHT}" \
  --return_score_weight "${RETURN_SCORE_WEIGHT}" \
  --return_listwise_weight "${RETURN_LISTWISE_WEIGHT}" \
  --return_positive_weight "${RETURN_POSITIVE_WEIGHT}" \
  --return_positive_margin_weight "${RETURN_POSITIVE_MARGIN_WEIGHT}" \
  --return_positive_margin "${RETURN_POSITIVE_MARGIN}" \
  --return_risk_suppression_weight "${RETURN_RISK_SUPPRESSION_WEIGHT}" \
  --return_risk_suppression_margin "${RETURN_RISK_SUPPRESSION_MARGIN}" \
  --return_exact_weight "${RETURN_EXACT_WEIGHT}" \
  --return_exact_min_gap "${RETURN_EXACT_MIN_GAP}" \
  --return_target_mode "${RETURN_TARGET_MODE}" \
  --return_explicit_pairwise_weight "${RETURN_EXPLICIT_PAIRWISE_WEIGHT}" \
  --return_explicit_pairwise_margin "${RETURN_EXPLICIT_PAIRWISE_MARGIN}" \
  --teacher_distill_weight "${TEACHER_DISTILL_WEIGHT}" \
  --teacher_distill_temperature "${TEACHER_DISTILL_TEMPERATURE}" \
  --topk_coverage_weight "${TOPK_COVERAGE_WEIGHT}" \
  --topk_coverage_k "${TOPK_COVERAGE_K}" \
  --topk_coverage_temperature "${TOPK_COVERAGE_TEMPERATURE}" \
  --macro_weight "${MACRO_WEIGHT}" \
  --checklist_class_weight "${CHECKLIST_CLASS_WEIGHT}" \
  --checklist_applicability_weight "${CHECKLIST_APPLICABILITY_WEIGHT}" \
  --detail_score_weight "${DETAIL_SCORE_WEIGHT}" \
  --why_tag_weight "${WHY_TAG_WEIGHT}" \
  --route_weight "${ROUTE_WEIGHT}" \
  --route_balanced_ce \
  --route_focal_gamma "${ROUTE_FOCAL_GAMMA}" \
  --route_object_single_margin_weight "${ROUTE_OBJECT_SINGLE_MARGIN_WEIGHT}" \
  --route_object_single_margin "${ROUTE_OBJECT_SINGLE_MARGIN}" \
  --route_hierarchy_weight "${ROUTE_HIERARCHY_WEIGHT}" \
  --route_cardinality_weight "${ROUTE_CARDINALITY_WEIGHT}" \
  --route_expert_distill_checkpoints "${ROUTE1}" "${ROUTE2}" "${ROUTE3}" \
  --route_expert_distill_weights "${ROUTE_EXPERT_DISTILL_WEIGHTS}" \
  --route_expert_distill_weight "${ROUTE_EXPERT_DISTILL_WEIGHT}" \
  --route_expert_distill_hard_weight "${ROUTE_EXPERT_DISTILL_HARD_WEIGHT}" \
  --decision_weight "${DECISION_WEIGHT}" \
  "${DECISION_ARGS[@]}" \
  --action_consistency_weight "${ACTION_CONSISTENCY_WEIGHT}" \
  --action_consistency_margin "${ACTION_CONSISTENCY_MARGIN}" \
  "${ACTION_SOURCE_ARGS[@]}" \
  --action_return_joint_weight "${ACTION_RETURN_JOINT_WEIGHT}" \
  --action_return_joint_score_margin "${ACTION_RETURN_JOINT_SCORE_MARGIN}" \
  --action_return_joint_logit_margin "${ACTION_RETURN_JOINT_LOGIT_MARGIN}" \
  --action_return_joint_temperature "${ACTION_RETURN_JOINT_TEMPERATURE}" \
  --return_source_margin_weight "${RETURN_SOURCE_MARGIN_WEIGHT}" \
  --return_source_margin_logit_margin "${RETURN_SOURCE_MARGIN_LOGIT_MARGIN}" \
  $([[ "${RETURN_SOURCE_MARGIN_BALANCED,,}" =~ ^(1|true|yes|on)$ ]] && printf '%s' '--return_source_margin_balanced') \
  --return_source_margin_balance_max_weight "${RETURN_SOURCE_MARGIN_BALANCE_MAX_WEIGHT}" \
  --return_source_margin_crop_weight_mult "${RETURN_SOURCE_MARGIN_CROP_WEIGHT_MULT}" \
  --decision_source_margin_weight "${DECISION_SOURCE_MARGIN_WEIGHT}" \
  --decision_source_logit_margin "${DECISION_SOURCE_LOGIT_MARGIN}" \
  $([[ "${DECISION_SOURCE_MARGIN_BALANCED,,}" =~ ^(1|true|yes|on)$ ]] && printf '%s' '--decision_source_margin_balanced') \
  --decision_source_margin_balance_max_weight "${DECISION_SOURCE_MARGIN_BALANCE_MAX_WEIGHT}" \
  --decision_source_margin_crop_weight_mult "${DECISION_SOURCE_MARGIN_CROP_WEIGHT_MULT}" \
  --decision_utility_align_weight "${DECISION_UTILITY_ALIGN_WEIGHT}" \
  --policy_score_weight "${POLICY_SCORE_WEIGHT}" \
  --delta_weight "${DELTA_WEIGHT}" \
  --proposal_weight "${PROPOSAL_WEIGHT}" \
  --proposal_subject_weight "${PROPOSAL_SUBJECT_WEIGHT}" \
  --subject_proposal_align_weight "${SUBJECT_PROPOSAL_ALIGN_WEIGHT}" \
  --subject_box_weight "${SUBJECT_BOX_WEIGHT}" \
  --subject_box_valid_weight "${SUBJECT_BOX_VALID_WEIGHT}" \
  --subject_box_l1_weight "${SUBJECT_BOX_L1_WEIGHT}" \
  --subject_box_iou_weight "${SUBJECT_BOX_IOU_WEIGHT}" \
  --subject_box_center_weight "${SUBJECT_BOX_CENTER_WEIGHT}" \
  --subject_box_size_weight "${SUBJECT_BOX_SIZE_WEIGHT}" \
  --subject_box_aspect_weight "${SUBJECT_BOX_ASPECT_WEIGHT}" \
  --subject_box_ciou_weight "${SUBJECT_BOX_CIOU_WEIGHT}" \
  --subject_box_valid_balanced_bce \
  --subject_box_valid_negative_scale "${SUBJECT_BOX_VALID_NEGATIVE_SCALE}" \
  --subject_box_spatial_aux_weight "${SUBJECT_BOX_SPATIAL_AUX_WEIGHT}" \
  --subject_box_spatial_heatmap_weight "${SUBJECT_BOX_SPATIAL_HEATMAP_WEIGHT}" \
  --subject_box_spatial_mask_weight "${SUBJECT_BOX_SPATIAL_MASK_WEIGHT}" \
  --generated_proposal_align_weight "${GENERATED_PROPOSAL_ALIGN_WEIGHT}" \
  --generated_proposal_score_weight "${GENERATED_PROPOSAL_SCORE_WEIGHT}" \
  --generated_proposal_listwise_weight "${GENERATED_PROPOSAL_LISTWISE_WEIGHT}" \
  --generated_proposal_positive_weight "${GENERATED_PROPOSAL_POSITIVE_WEIGHT}" \
  --generated_proposal_risk_weight "${GENERATED_PROPOSAL_RISK_WEIGHT}" \
  --generated_proposal_positive_utility_weight "${GENERATED_PROPOSAL_POSITIVE_UTILITY_WEIGHT}" \
  --generated_proposal_positive_margin_weight "${GENERATED_PROPOSAL_POSITIVE_MARGIN_WEIGHT}" \
  --generated_proposal_positive_margin "${GENERATED_PROPOSAL_POSITIVE_MARGIN}" \
  --generated_proposal_match_iou "${GENERATED_PROPOSAL_MATCH_IOU}" \
  --selection_metric "${SELECTION_METRIC}" \
  --progress_log_interval 25 \
  --device cuda \
  2>&1 | tee "${OUT_DIR}/train.log"

date -u +"end_utc=%Y-%m-%dT%H:%M:%SZ" | tee -a "${OUT_DIR}/environment.log"

if [[ "${ENABLE_TRAIN_GATE,,}" =~ ^(1|true|yes|on)$ ]]; then
  /usr/local/bin/python3 - <<PY
import json
import time
from pathlib import Path

summary_path = Path(${OUT_DIR@Q}) / "summary.json"
decision_path = Path(${OUT_DIR@Q}) / "train_gate_decision.json"
pass_path = Path(${OUT_DIR@Q}) / ".train_gate_pass"
status_path = Path(${STATUS@Q})
thresholds = {
    "route_balanced_acc": float(${TRAIN_GATE_ROUTE_BALANCED_MIN@Q}),
    "subject_box_iou": float(${TRAIN_GATE_SUBJECT_IOU_MIN@Q}),
    "subject_box_valid_best_balanced_acc": float(${TRAIN_GATE_SUBJECT_VALID_BALANCED_MIN@Q}),
    "proposal_recall_0_5": float(${TRAIN_GATE_PROPOSAL_RECALL_MIN@Q}),
    "generated_align_top1_hit": float(${TRAIN_GATE_GENERATED_ALIGN_MIN@Q}),
}
return_target_mode = str(${RETURN_TARGET_MODE@Q} or "score").lower()
use_decision_conditioned = str(${RETURN_SCORE_DECISION_CONDITIONED@Q} or "0").lower() in {"1", "true", "yes", "on"}
use_source_mixture = str(${RETURN_SCORE_SOURCE_MIXTURE@Q} or "0").lower() in {"1", "true", "yes", "on"}
use_source_gate = str(${RETURN_SCORE_SOURCE_GATE@Q} or "0").lower() in {"1", "true", "yes", "on"}
summary = json.loads(summary_path.read_text(encoding="utf-8")) if summary_path.exists() else {}
row = summary.get("best_row") or summary.get("last_row") or {}
val = row.get("val") or {}
def pick_surface_key(suffix: str) -> str:
    source_gate_key = f"source_gate_{suffix}"
    if use_source_gate and val.get(source_gate_key) is not None:
        return source_gate_key
    source_key = f"source_mixture_{suffix}"
    if use_source_mixture and val.get(source_key) is not None:
        return source_key
    conditioned_key = f"decision_conditioned_{suffix}"
    if use_decision_conditioned and val.get(conditioned_key) is not None:
        return conditioned_key
    return suffix

crop_action_key = pick_surface_key("crop_action_top1_hit")
top_return_key = pick_surface_key("top_return_hit")
baseline_key = pick_surface_key("baseline_preserve_top1_hit")
thresholds[crop_action_key] = float(${TRAIN_GATE_ACTION_TOP1_MIN@Q})
thresholds[top_return_key] = float(${TRAIN_GATE_TOP_RETURN_MIN@Q})
metrics = {key: val.get(key) for key in thresholds}
baseline_target_rate = val.get("baseline_preserve_target_rate")
raw_top_key = None
raw_gate_mode = str(${TRAIN_GATE_RAW_TOP_RETURN_MODE@Q} or "auto").strip().lower()
if return_target_mode in {"decision_source", "decision_consistent", "action_source"}:
    raw_top_key = pick_surface_key("raw_top_return_hit")
    apply_raw_gate = val.get(raw_top_key) is not None
    if raw_gate_mode in {"0", "false", "no", "off", "never", "none", "disabled"}:
        apply_raw_gate = False
    elif raw_gate_mode in {"auto", "mixed", "nonempty_baseline"}:
        apply_raw_gate = apply_raw_gate and (
            baseline_target_rate is None
            or float(baseline_target_rate) >= float(${TRAIN_GATE_BASELINE_TARGET_RATE_MIN@Q})
        )
    elif raw_gate_mode not in {"1", "true", "yes", "on", "always"}:
        raise ValueError(f"unsupported TRAIN_GATE_RAW_TOP_RETURN_MODE={raw_gate_mode!r}")
    if apply_raw_gate:
        thresholds[raw_top_key] = float(${TRAIN_GATE_TOP_RETURN_MIN@Q})
        metrics[raw_top_key] = val.get(raw_top_key)
if baseline_target_rate is not None and float(baseline_target_rate) >= float(${TRAIN_GATE_BASELINE_TARGET_RATE_MIN@Q}):
    thresholds[baseline_key] = float(${TRAIN_GATE_BASELINE_PRESERVE_MIN@Q})
    metrics[baseline_key] = val.get(baseline_key)
    metrics["baseline_preserve_target_rate"] = baseline_target_rate
failures = {
    key: {"value": metrics.get(key), "threshold": threshold}
    for key, threshold in thresholds.items()
    if metrics.get(key) is None or float(metrics.get(key)) < threshold
}
passed = not failures
payload = {
    "state": "train_gate_passed" if passed else "excluded_train_gate",
    "run_name": ${RUN_NAME@Q},
    "created_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "summary": str(summary_path),
    "best_epoch": summary.get("best_epoch"),
    "best_selection_score": summary.get("best_selection_score"),
    "thresholds": thresholds,
    "metrics": metrics,
    "failures": failures,
    "return_target_mode": return_target_mode,
    "raw_top_return_gate_applied": bool(raw_top_key is not None and raw_top_key in thresholds),
    "raw_top_return_gate_mode": raw_gate_mode,
    "next_action": "run embedded no-prior direct/head/qualitative gate" if passed else "skip GPU gate and mark excluded",
}
decision_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
pass_path.write_text("1\n" if passed else "0\n", encoding="utf-8")
if not passed:
    status_path.parent.mkdir(parents=True, exist_ok=True)
    status_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(json.dumps(payload, ensure_ascii=False))
PY
  if [[ "$(tr -d '[:space:]' < "${OUT_DIR}/.train_gate_pass")" != "1" ]]; then
    echo "train gate failed; skip embedded/direct/qualitative gate" | tee -a "${OUT_DIR}/environment.log"
    exit 0
  fi
fi

/usr/local/bin/python3 src/scripts/embed_mobilecropnet_v4_route_experts.py \
  --mobilecropnet_checkpoint "${OUT_DIR}/best.pt" \
  --route_expert_checkpoints "${EMBED_ROUTE}" \
  --output_checkpoint "${EMBED}" \
  --note "quality_relaxed_joint_${MODEL_PROFILE}_swinroute"

RUN_TAG="${GATE_TAG}" \
CHECKPOINT="${EMBED}" \
ROUTE_EXPERT_MODE=none \
EVAL_JSONL="${EVAL_JSONL}" \
HEAD_OUT="${HEAD_OUT}" \
DIRECT_OUT="${DIRECT_OUT}" \
SUBJECT_VALID_THRESHOLD="${SUBJECT_VALID_THRESHOLD}" \
SUBJECT_VALID_POLICY="${SUBJECT_VALID_POLICY}" \
SUBJECT_BOX_TARGET_SOURCE="${SUBJECT_BOX_TARGET_SOURCE}" \
USE_DECISION_SOURCE_ACTION_GATE="$(
  if [[ "${USE_DECISION_SOURCE_ACTION_GATE:-}" =~ ^(0|false|no|off)$ ]]; then
    printf '0'
  elif [[ "${USE_DECISION_SOURCE_ACTION_GATE:-}" =~ ^(1|true|yes|on)$ || "${RETURN_SCORE_SOURCE_GATE,,}" =~ ^(1|true|yes|on)$ || "${DECISION_SOURCE_HEAD,,}" =~ ^(1|true|yes|on)$ || "${DECISION_SOURCE_PAIR_HEAD,,}" =~ ^(1|true|yes|on)$ ]]; then
    printf '1'
  else
    printf '0'
  fi
)" \
MAX_ROWS="${MAX_GATE_ROWS}" \
AUDIT_BATCH_SIZE="${AUDIT_BATCH_SIZE}" \
DIRECT_BATCH_SIZE="${DIRECT_BATCH_SIZE}" \
NUM_WORKERS="${NUM_WORKERS}" \
STATUS_JSON="${STATUS}" \
bash src/scripts/run_mobilecropnet_v4_composite_routeaware_gate.sh

/usr/local/bin/python3 src/scripts/build_mobilecropnet_v4_composite_qualitative_pack.py \
  --direct_predictions_jsonl "${DIRECT_OUT}/predictions.jsonl" \
  --output_dir "${QUAL_OUT}" \
  --checkpoint "${EMBED}" \
  --subject_valid_threshold "${SUBJECT_VALID_THRESHOLD}" \
  --max_per_bucket 24 \
  --max_total 120
